//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacman.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pacman.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0vies {
            get {
                object obj = ResourceManager.GetObject("_0vies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1vies {
            get {
                object obj = ResourceManager.GetObject("_1vies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2vies {
            get {
                object obj = ResourceManager.GetObject("_2vies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3vies {
            get {
                object obj = ResourceManager.GetObject("_3vies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bas {
            get {
                object obj = ResourceManager.GetObject("bas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bleu_bas {
            get {
                object obj = ResourceManager.GetObject("bleu_bas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bleu_haut {
            get {
                object obj = ResourceManager.GetObject("bleu_haut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bleu_left {
            get {
                object obj = ResourceManager.GetObject("bleu_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bleu_right {
            get {
                object obj = ResourceManager.GetObject("bleu_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap droite {
            get {
                object obj = ResourceManager.GetObject("droite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fuite_bas {
            get {
                object obj = ResourceManager.GetObject("fuite_bas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fuite_blinky {
            get {
                object obj = ResourceManager.GetObject("fuite_blinky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fuite_doite {
            get {
                object obj = ResourceManager.GetObject("fuite_doite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fuite_gauche {
            get {
                object obj = ResourceManager.GetObject("fuite_gauche", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fuite_haut {
            get {
                object obj = ResourceManager.GetObject("fuite_haut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gauche {
            get {
                object obj = ResourceManager.GetObject("gauche", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap haut {
            get {
                object obj = ResourceManager.GetObject("haut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icones_Interface {
            get {
                object obj = ResourceManager.GetObject("Icones_Interface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icones_Interface2 {
            get {
                object obj = ResourceManager.GetObject("Icones_Interface2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Interface_Bas {
            get {
                object obj = ResourceManager.GetObject("Interface_Bas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 11111111111111111111111111111111111111
        ///13221222221222222222222222212222212231
        ///12221211121211112111121111212111212221
        ///12222211121211222211222211212111222221
        ///11112222222222212222221222222222221111
        ///01222112112112112111121121121121122210
        ///01212222222222212111121222222222221210
        ///01212111111112000111100021111111121210
        ///01212112221112100000000121112221121210
        ///11212222122222101199110122222122221211
        ///00211112112112101000010121121121111200
        ///11212222112112101567810121121122221211
        ///01212112222222101111110122222221 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Map01 {
            get {
                return ResourceManager.GetString("Map01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 11111111111111111111111111111111111111
        ///13221222222222222211222222222222212231
        ///12221212111112121222212121111121212221
        ///12222212222222122211222122222221222221
        ///11112111111111121111112111111111121111
        ///11222221122222222222222222222112222211
        ///01212122221212111111111121212222121210
        ///01212121122212000000000021222112121210
        ///01222222221112100000000121112222222210
        ///11112121122222101199110122222112121111
        ///00222221121111101000010111112112222200
        ///11112121122222101567810122222112121111
        ///01222222221112001111110021112222 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Map02 {
            get {
                return ResourceManager.GetString("Map02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 11111111111111111111111111111111111111
        ///13221222122211122222222111222122212231
        ///12221212221222221111112222212221212221
        ///12222211111111121111112111111111222221
        ///11111222222222222222222222222222211111
        ///12221211111111121111112111111111212221
        ///12122221222112221222212221122212222121
        ///12112122212222101211210122221222121121
        ///12222221111212100000000121211112222221
        ///11121122222212001199110021222222112111
        ///00221111211112101000010121111211112200
        ///11122222211222101567810122211222222111
        ///12221121112212101111110121221112 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Map03 {
            get {
                return ResourceManager.GetString("Map03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 11111111111111111111111111111111111111
        ///13221222222222211222211222222222212231
        ///12221211111111222211222211111111212221
        ///12222222222222211211211222222222222221
        ///11112111121111212222221211112111121111
        ///01222221222122222111122222122212222210
        ///01211122212221212222221212221222111210
        ///01222221212111210111101211121212222210
        ///01212112222222000000000022222221121210
        ///11212122121212101199110121212122121211
        ///00212121121222101000010122212112121200
        ///11212221121211101567810111212112221211
        ///01212122122222101111110122222122 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MapFeu {
            get {
                return ResourceManager.GetString("MapFeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 11111111111111111111111111111111111111
        ///13221222222222222222222222222222212231
        ///12221211211112121111112121111211212221
        ///12222222222212122211222121222222222221
        ///11112121121222211222211222212112121111
        ///00222222221211211111111211212222222200
        ///11211212122222222222222222222121211211
        ///01222212221112111011011121112221222210
        ///11212112122212000000000021222121121211
        ///00212112121222101199110122212121121200
        ///11212222221121101222210112112222221211
        ///01222121121121101567810112112112122210
        ///11212122222222001111110022222222 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MapGlace {
            get {
                return ResourceManager.GetString("MapGlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mur {
            get {
                object obj = ResourceManager.GetObject("mur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mur2 {
            get {
                object obj = ResourceManager.GetObject("mur2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MUR4 {
            get {
                object obj = ResourceManager.GetObject("MUR4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MUR5 {
            get {
                object obj = ResourceManager.GetObject("MUR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap murBase {
            get {
                object obj = ResourceManager.GetObject("murBase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MurFeu {
            get {
                object obj = ResourceManager.GetObject("MurFeu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MurGlace {
            get {
                object obj = ResourceManager.GetObject("MurGlace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orange_bas {
            get {
                object obj = ResourceManager.GetObject("orange_bas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orange_haut {
            get {
                object obj = ResourceManager.GetObject("orange_haut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orange_left {
            get {
                object obj = ResourceManager.GetObject("orange_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orange_right {
            get {
                object obj = ResourceManager.GetObject("orange_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap piece {
            get {
                object obj = ResourceManager.GetObject("piece", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pink_bas {
            get {
                object obj = ResourceManager.GetObject("pink_bas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pink_droite {
            get {
                object obj = ResourceManager.GetObject("pink_droite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pink_haut {
            get {
                object obj = ResourceManager.GetObject("pink_haut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pink_left {
            get {
                object obj = ResourceManager.GetObject("pink_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rouge {
            get {
                object obj = ResourceManager.GetObject("rouge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap superPiece {
            get {
                object obj = ResourceManager.GetObject("superPiece", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yeux_bas {
            get {
                object obj = ResourceManager.GetObject("yeux_bas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yeux_blinky {
            get {
                object obj = ResourceManager.GetObject("yeux_blinky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yeux_droite {
            get {
                object obj = ResourceManager.GetObject("yeux_droite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yeux_gauche {
            get {
                object obj = ResourceManager.GetObject("yeux_gauche", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yeux_haut {
            get {
                object obj = ResourceManager.GetObject("yeux_haut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
